config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens

  namespace :api do
    namespace :v1 do
      resources :kittens, only: [:index]
    end
  end
end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/api/v1/kittens_controller.rb
class Api::V1::KittensController < ActionController::API
  def index
    render json: Kitten.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    @kittens.as_json
  end

  def show
    @kitten = Kitten.find(params[:id])
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Cuteness saved!"
      redirect_to kittens_path
    else
      flash.now[:error] = @kitten.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "All that cute, updated!"
      redirect_to kitten_path
    else
      flash.now[:error] = "Cute update fail"
      render :edit
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to kittens_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kittens/edit.html.erb
<%= render "shared/kitten_form" %>
<%= link_to "Delete", kitten_path(@kitten) %>

app/views/kittens/index.html.erb
<% @kittens.each do |kitten| %>
  <li><%= link_to kitten.name, kitten %>
  <%= link_to "Delete", kitten_path(kitten), method: "delete  " %></li>
<% end %>
<%= link_to "Add new kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<%= render "shared/kitten_form" %>

app/views/kittens/show.html.erb
<%= @kitten.name %><br>
<%= @kitten.age %><br>
<%= @kitten.cuteness %><br>
<%= @kitten.softness %><br>
<%= link_to "Edit kitten", edit_kitten_path %><br>
<%= link_to "Delete", kitten_path(@kitten), method: "delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:success] %>
  <%= flash[:success] %>
<% elsif flash[:error] %>
  <%= flash[:error] %>
<% end %>
<%= yield %>

</body>
</html>

app/views/shared/_kitten_form.html.erb
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :age %>
  <%= f.text_field :age %><br>

  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %><br>

  <%= f.label :softness %>
  <%= f.text_field :softness %><br>

  <%= f.submit %>
<% end %>